# These are supported funding model platforms
patreon: doobdev # Replace with a single Patreon username
ko_fi: mmatt # Replace with a single Ko-fi username
liberapay: mmatt # Replace with a single Liberapay username
custom: https://subs.twitch.tv/mmattbtw # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
